### ISSUE TITLE
TreeDefinition

### ISSUE THREAD

**Issue by FriedrGo** [fidley/ADT-Classic-Outline-Backend#17]
Hi,

I am playing around with this extension trying to promote it in our organization. There it comes with some questions.

The extension seems to work on systems where the include is not installed.
- How does it make the connection?
- Is it one time just for getting the definition?

Which would lead me to the second question:
- We are using a programming template for reports, which comes with a custom tree to find the relevant spots for enhancement
- Would it be possible to load more than one tree definition and switch between them? Maybe even automatically?

Would like to hear from you - maybe even enhancing this together for distribution...

Best regards,
FriedGo

**Comment by fidley** [comment]
Hi @FriedrGo,
the extension must have backend component installed. In other case it should show such message:
![image](https://github.com/fidley/ADT-Classic-Outline-Backend/assets/7912195/2f371d94-95e4-4fba-9634-9d7ddf87c89c)
If this does not happen, then it could be that the refresh of the tree is broken (it happens to me one a while, but cannot reproduce this during debugging, so cannot find why).

It can also happen, then when you are at first on the system where you have the backend installed, then you switch to embedded SAP GUI on the system in which backend component is not installed, then the tree from previous editor is still visible. It's because I catch the specific editor activation. 

> Would it be possible to load more than one tree definition and switch between them? Maybe even automatically?
This is exactly done in the plugin. I create tree for each system and object and I keep them in the memory. When you switch between the editor tabs, change the displayed tree in the plugin. The refresh is done at save, activation or at demand.

Cheers
Łukasz

**Comment by FriedrGo** [comment]
Hi Łukasz,

thanks for explanation - I found the backend installed as local object by a colleague - that explains the mistery why it worked without me installing the backend.

So this can be closed - but as I have another issue I am trying to contact you via linkedIn for a PM.

Best regards,
FriedrGo
